"""Added chat field to newsletter

Revision ID: 6e8e131eeb43
Revises: 8a8e860a046c
Create Date: 2023-08-15 14:42:27.307691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e8e131eeb43'
down_revision = '8a8e860a046c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter', sa.Column('chat', postgresql.ARRAY(sa.JSON()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter', 'chat')
    # ### end Alembic commands ###
