"""Added template field to digest (for now only contains section template)

Revision ID: 8a8e860a046c
Revises: eb99e7510ea0
Create Date: 2023-08-15 13:28:56.190976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8e860a046c'
down_revision = 'eb99e7510ea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digest', sa.Column('template', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digest', 'template')
    # ### end Alembic commands ###
