"""empty message

Revision ID: 45a552e007e3
Revises: 0c88dcee944d
Create Date: 2023-07-09 17:41:46.284584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a552e007e3'
down_revision = '0c88dcee944d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_uuid'), ['uuid'], unique=False)

    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=False)

    op.create_table('digests',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digests_uuid'), ['uuid'], unique=False)

    op.create_table('newsletters',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('digest_uuid', sa.UUID(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('html', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['digest_uuid'], ['digests.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletters_uuid'), ['uuid'], unique=False)

    op.create_table('newsletter_article',
    sa.Column('newsletter', sa.UUID(), nullable=False),
    sa.Column('article', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article'], ['articles.uuid'], ),
    sa.ForeignKeyConstraint(['newsletter'], ['newsletters.uuid'], ),
    sa.PrimaryKeyConstraint('newsletter', 'article')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_article')
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletters_uuid'))

    op.drop_table('newsletters')
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digests_uuid'))

    op.drop_table('digests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_uuid'))
        batch_op.drop_index(batch_op.f('ix_articles_url'))
        batch_op.drop_index(batch_op.f('ix_articles_source'))
        batch_op.drop_index(batch_op.f('ix_articles_author'))

    op.drop_table('articles')
    # ### end Alembic commands ###
