"""empty message

Revision ID: 2c74cf48b79c
Revises: 4ef2163d3a0a
Create Date: 2023-06-18 10:37:25.828982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c74cf48b79c'
down_revision = '4ef2163d3a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.drop_column('newsletter')

    # ### end Alembic commands ###
